### ISSUE TITLE
[BUG] The plugin needs a bit of "how to use" doccumentation.

### ISSUE THREAD

**Issue by CraigEwert** [aroary/lorem_ipsum#38]
**Describe the bug**
I cant find any instructions how to use the plugin.  I had to read the code to discover the commands.

**To Reproduce**
1. install the plugin
2. open a document
3. place the cursor where you want some text
4. ????

**Expected behavior**
A paragraph or 2 in the README or nearby, with a list of the command words. Possibly also a recap of the \<F1\> method of opening the command window (for newer users of VSCode).

Once I did find the commands, it works great.

**Desktop (please complete the following information):**
 - OS: macos
 - Version 1.3.2

**Comment by aroary** [comment]
There is a wiki about how to run commans here: https://github.com/aroary/lorem_ipsum/wiki
The wiki is not displayed on the extension page but an abridged version should be added.
